### ISSUE TITLE
about NodeProcessor

### ISSUE THREAD

**Issue by AlisaBen** [songyaheng/sparkNLP#2]
想问下作者，Trie中的NodeProcessor的作用是什么？没有看懂这里

**Comment by songyaheng** [comment]
这个用在树的join等操作的时候
![image](https://user-images.githubusercontent.com/18136199/38865057-466519e0-426f-11e8-81c4-f54e9eb2098b.png)
在做join实现的时候我们会做这个方法的具体实现，就是一种面向接口编程的方式。
![image](https://user-images.githubusercontent.com/18136199/38865196-b54159aa-426f-11e8-93e3-e251779fa316.png)
而那个trie树构造是一个通用型的
